version: '3.7'
services:
  dynamodb:
    build: .
    volumes:
      - data:/home/dynamodblocal/data
    ports:
    - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath ./data
  dynamodb-admin:
    image: instructure/dynamo-local-admin
    ports:
    - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000/
volumes:
  data: